name: build_app

on: [push, pull_request]

jobs:
  build:
    runs-on: macOS-latest
    name: Xcode ${{ matrix.xcode }}
    strategy:
      matrix:
        xcode: ["11.4"]
    steps:
    - uses: webfactory/ssh-agent@v0.2.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
    - name: (WORKAROUND) Use private swift package manager
      run: |
        for ip in $(dig @8.8.8.8 github.com +short); do ssh-keyscan github.com,$ip; ssh-keyscan $ip; done 2>/dev/null >> ~/.ssh/known_hosts
    - uses: actions/checkout@v2
    - name: Setup Xcode
      run: |
        echo "Available Xcode versions:"
        ls /Applications | grep Xcode
        echo "Choosing Xcode_${{ matrix.xcode }}.app"
        sudo xcode-select -s /Applications/Xcode_${{ matrix.xcode }}.app
    - name: Decrypt
      run: ./scripts/decrypt.sh
      env:
        SECRET_PASSPHRASE: ${{ secrets.SECRET_PASSPHRASE }}
    - name: Build
      run: ./scripts/build.sh
